### PR TITLE
DB base config files to start the project

### PR DESCRIPTION
**Pull request by Donaldblanc**
added a git ignore, created package Json with base dependency, default skeleton webpack config file

### CODE REVIEW

**Review by saylestyler — APPROVED** [review]
👍 lgtm

**Comment by jaeroong** [comment]
ok

**Review by RealJoelRivera — APPROVED** [review]

**Review by RealJoelRivera — APPROVED** [review]

**Review by jaeroong — COMMENTED** [review]
ok

**Review by RealJoelRivera — APPROVED** [review]

**Review by jaeroong — APPROVED** [review]
approved

**Pull request merged**
