### PR TITLE
add base file structure for node cli app { /bin/bin + /src/cli.js }

### PR DESCRIPTION
**Pull request by saylestyler**

### CODE REVIEW

**Comment by Donaldblanc** [comment]
looking good on the basic folder structure

**Review by Donaldblanc — APPROVED** [review]
looks good here

**Review by RealJoelRivera — APPROVED** [review]

**Review by jaeroong — CHANGES_REQUESTED** [review]
ok

**Review by jaeroong — APPROVED** [review]
ok

**Pull request merged**
